name: dmcgb
channels:
  - defaults
dependencies:
  - python=3.8.12
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip=21
  - pip:
    - numpy==1.20.0
    - torch==1.13.1 
    - torchvision==0.14.1
    - pillow==8.4.0
    - setuptools==65.5.1
    - wheel==0.38.0
    - termcolor
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - tqdm
    - einops
    - kornia
    - pyvirtualdisplay==3.0
    - pandas==1.3.5
    - wandb